# Generated by Django 5.1.6 on 2025-02-14 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_post_profile'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_comments', to='profiles.profile'),
        ),
    ]
